# Generated by Django 5.2.6 on 2025-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=155, verbose_name='Бранд')),
                ('model', models.CharField(max_length=155, verbose_name='Модел')),
                ('number', models.CharField(max_length=50, verbose_name='Номер машины')),
                ('probeg', models.CharField(max_length=155, verbose_name='Пробег')),
                ('carabka_transfer', models.CharField(choices=[('Автомат', 'Автомат'), ('Механика', 'Механика'), ('Эдекторкар', 'Эдекторкар')], default=None, max_length=155, verbose_name='карабока передачи')),
                ('type_car', models.CharField(choices=[('Седан', 'Седан'), ('Универсал', 'Универсал'), ('Грузовой', 'Универсал')], default=None, max_length=155, verbose_name='Тип ')),
                ('date', models.CharField(max_length=100, verbose_name='Год Выпуска')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
